---

# Cluster Configurations
cluster_name: ''
cluster_type: 'poc' # (poc|rhpds|dev)

# Workflow Job Template
integreatly_workflow_job_template_name: 'Integreatly Install Workflow'
integreatly_workflow_job_template_desc: 'Workflow for Installing Integreatly against a target Openshift Cluster'
integreatly_workflow_job_template_organization: "{{ tower_organization }}"

# Integreatly Credentials
integreatly_credential_bundle_github_name: "dummy-scm-credentials"
integreatly_credential_bundle_github_desc: "Dummy SCM credentials for Integreatly project"
integreatly_credential_bundle_github_kind: 'scm'

# Integreatly Job Templates
integreatly_job_template_bootstrap_name: 'Integreatly Bootstrap Cluster Template'
integreatly_job_template_bootstrap_desc: 'Job for bootstrapping integreatly cluster resources'
integreatly_job_template_bootstrap_type: 'run'
integreatly_job_template_bootstrap_playbook: 'playbooks/bootstrap_integreatly_install.yml'
integreatly_job_template_bootstrap_credentials: "{{ tower_credential_bundle_default_name }}"

integreatly_job_template_deploy_name: 'Integreatly Deploy Job Template'
integreatly_job_template_deploy_desc: 'Job for deploying Integreatly on target Openshift cluster'
integreatly_job_template_deploy_type: 'run'
integreatly_job_template_deploy_playbook: 'playbooks/install.yml'
integreatly_job_template_deploy_credentials: "{{ tower_credential_bundle_default_name }}"

# Integreatly Projects
integreatly_project_bootstrap_cluster_scm_branch: ''
integreatly_project_bootstrap_cluster_name: "integreatly-install-{{ integreatly_project_bootstrap_cluster_scm_branch }}"
integreatly_project_bootstrap_cluster_desc: "Integreatly Project for Branch: {{ integreatly_project_bootstrap_cluster_scm_branch }}"
integreatly_project_bootstrap_cluster_scm_type: git
integreatly_project_bootstrap_cluster_scm_clean: true
integreatly_project_bootstrap_cluster_scm_url: ''
integreatly_project_bootstrap_cluster_scm_update_on_launch: true
integreatly_project_bootstrap_cluster_scm_delete_on_update: true

# Integreatly Inventories
integreatly_inventory_name: "{{ cluster_name }}"
integreatly_inventory_desc: "Integreatly Inventory: {{ cluster_name }}"

# Integreatly Sources
integreatly_inventory_source_aws_name: "{{ cluster_name }}-inventory-source-aws"
integreatly_inventory_source_aws_type: 'ec2'
integreatly_inventory_source_aws_update_on_launch: false
integreatly_inventory_source_aws_overwrite: false
integreatly_inventory_source_aws_credentials: ''
integreatly_inventory_source_aws_regions: 'All'
integreatly_inventory_source_aws_instance_filters: "tag:clusterid={{ cluster_name }}"

integreatly_inventory_source_project_name: "{{ cluster_name }}-inventory-source-project-{{ integreatly_project_bootstrap_cluster_name }}"
integreatly_inventory_source_project_type: 'scm'
integreatly_inventory_source_project_path: "inventories/"
integreatly_inventory_source_project_update_on_launch: false
integreatly_inventory_source_project_overwrite: false
integreatly_inventory_source_project_overwrite_vars: false

# Integreatly Groups
integreatly_group_master_name: 'master'
integreatly_group_master_desc: "Master group: {{ cluster_name }}"
integreatly_group_master_overwrite: true
integreatly_group_master_overwrite_vars: true
integreatly_group_master_update_on_launch: false
integreatly_group_master_aws_name: 'tag_host_type_master'

integreatly_group_local_name: 'local'
integreatly_group_local_desc: "Local group: {{ cluster_name }}"
integreatly_group_local_overwrite: true
integreatly_group_local_overwrite_vars: true
integreatly_group_local_update_on_launch: false

# Integreatly Hosts
integreatly_host_local_name: 'localhost'
integreatly_host_local_desc: "Localhost: {{ cluster_name }}"
