---
- name: post-install tasks
  hosts: localhost
  tasks:
  - name: Get instance facts
    ec2_instance_facts:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ oo_sublocation }}"
        filters: "tag:clusterid={{ oo_clusterid }},tag:host-type=master"
    register: facts

  - name: add first master to firstMaster group
    add_host:
      name: "{{ facts.instances[0]['public_dns_name'] }}"
      groups: "firstMaster"

  - name: "Delete s3 IAM user for {{ oo_clusterid }}-backups if it exists"
    iam:
      iam_type: user
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      name: "{{ oo_clusterid }}-backups"
      state: absent
    ignore_errors: yes

  - name: "Create s3 IAM user for {{ oo_clusterid }}-backups"
    iam:
      iam_type: user
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      name: "{{ oo_clusterid }}-backups"
      state: present
      access_key_state: create
    register: iam_user

  - name: Set key facts
    set_fact:
      iam_access_key: "{{ iam_user.user_meta.access_keys[0].access_key_id }}"
      iam_secret_key: "{{ iam_user.user_meta.access_keys[0].secret_access_key }}"
      cacheable: true
      no_log: true

  - name: Generate IAM policy document
    template:
      src: roles/cluster/templates/iam_backups_policy.json.j2
      dest: /tmp/iam_policy.json

  - name: "Add s3-backup-access-{{ oo_clusterid }} policy to backups user"
    iam_policy:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      iam_type: user
      iam_name: "{{ oo_clusterid }}-backups"
      policy_name: s3-backup-access-{{ oo_clusterid }}
      policy_document: "/tmp/iam_policy.json"
      state: present

- name: create cluster-admin
  hosts: firstMaster
  vars:
    default_user: "integreatly"
  tasks:
  - name: Give cluster-admin to htpasswd user
    shell: oc adm policy add-cluster-role-to-user cluster-admin "{{ default_user }}"

  - name: Create backup namespace
    shell: "oc create namespace {{ cluster_backup_namespace }}"
    register: backup_namespace_result
    failed_when: backup_namespace_result.stderr != '' and 'AlreadyExists' not in backup_namespace_result.stderr

  - name: Create secret for backups
    shell: "oc create secret generic {{ cluster_backup_secret_name }} --from-literal=aws_access_key={{ hostvars['localhost']['iam_access_key'] }} --from-literal=aws_secret_key={{ hostvars['localhost']['iam_secret_key'] }} --from-literal=bucket_name={{ cluster_backup_bucket_name }} -n {{ cluster_backup_namespace }}"
    no_log: true
  
  - name: Retrieving IP addresses of master nodes
    shell: "oc get nodes -o wide | grep master | awk '{ print $7 }'"
    register: master_node_ip_addresses

  - name: Cluster Details
    debug:
      msg: "{{ item }}"
    with_items:
    - "Console URL: {{ openshift_master_public_console_url }}"
    - "Admin username: {{ openshift_master_htpasswd_users.keys() }}"
    - "Master node IP addresses: {{ master_node_ip_addresses.stdout_lines }}"