---
- hosts: master
  tasks:
    - name: "Clone the repo"
      git:
        repo: https://github.com/integr8ly/installation.git
        dest: /tmp/intly-installation
    - name: "Execute the playbook"
      shell: cd /tmp/intly-installation/evals && /usr/bin/ansible-playbook -i inventories/hosts.template playbooks/install.yml
      register: shell_output
    - name: "Print the output from the integreatly installer"
      debug:
        var: shell_output.stdout_lines
