---
# executing a playbook and prompting for vault pass:
# ansible-playbook --ask-vault-pass ansible_vault_testing.yml
- hosts: localhost
  connection: local
  tasks:
  - name: "Send the integreately POC provisioning email via sendgrid"
    include_role:
      name: sendgrid
      tasks_from: main
